create table portfolio
(
    id            uuid         not null,
    name          varchar(100) not null,
    base_currency varchar(3)   not null,
    created_at    timestamp    not null,
    version       bigint       not null default 0,
    constraint pk_portfolio primary key (id)
);

create table stock_position
(
    id              uuid         not null,
    portfolio_id    uuid         not null,
    symbol          varchar(20)  not null,
    instrument_name varchar(200) not null,
    isin            varchar(12),
    wkn             varchar(6),
    currency        varchar(3)   not null,
    constraint pk_position primary key (id),
    constraint fk_position_portfolio foreign key (portfolio_id) references portfolio (id) on delete cascade,
    constraint ux_position_symbol unique (portfolio_id, symbol)
);

create table tranche
(
    id              bigint generated by default as identity,
    position_id     uuid           not null,
    quantity        numeric(19, 6) not null,
    price_per_share numeric(19, 6) not null,
    fee             numeric(19, 6) not null default 0,
    trade_date      date           not null,
    constraint pk_tranche primary key (id),
    constraint fk_tranche_position foreign key (position_id) references stock_position (id) on delete cascade
);

create table realized_trade
(
    id                   bigint generated by default as identity,
    position_id          uuid           not null,
    quantity             numeric(19, 6) not null,
    buy_price_per_share  numeric(19, 6) not null,
    sell_price_per_share numeric(19, 6) not null,
    fees                 numeric(19, 6) not null default 0,
    buy_date             date           not null,
    sell_date            date           not null,
    constraint pk_realized_trade primary key (id),
    constraint fk_realized_trade_position foreign key (position_id) references stock_position (id) on delete cascade
);

create index ix_position_portfolio on stock_position (portfolio_id);
create index ix_tranche_position on tranche (position_id);
create index ix_realized_trade_position on realized_trade (position_id);
