-- A starter catalogue: the instruments of the legacy positions.json plus the usual suspects,
-- so search and the portfolio import have something to resolve against on a fresh database.
insert into instrument (symbol, name, isin, wkn, currency, exchange, type) values
  ('AAPL',    'Apple Inc.',                                'US0378331005', '865985', 'USD', 'NASDAQ', 'STOCK'),
  ('MSFT',    'Microsoft Corporation',                     'US5949181045', '870747', 'USD', 'NASDAQ', 'STOCK'),
  ('AMZN',    'Amazon.com Inc.',                           'US0231351067', '906866', 'USD', 'NASDAQ', 'STOCK'),
  ('GOOGL',   'Alphabet Inc. Class A',                     'US02079K1079', 'A14Y6F', 'USD', 'NASDAQ', 'STOCK'),
  ('NVDA',    'NVIDIA Corporation',                        'US67066G1040', '918422', 'USD', 'NASDAQ', 'STOCK'),
  ('TSLA',    'Tesla Inc.',                                'US88160R1014', 'A1CX3T', 'USD', 'NASDAQ', 'STOCK'),
  ('BRK-B',   'Berkshire Hathaway Inc. Class B',           'US0846707026', 'A0YJQ2', 'USD', 'NYSE',   'STOCK'),
  ('JNJ',     'Johnson & Johnson',                         'US4781601046', '853260', 'USD', 'NYSE',   'STOCK'),
  ('SAP.DE',  'SAP SE',                                    'DE0007164600', '716460', 'EUR', 'XETRA',  'STOCK'),
  ('SIE.DE',  'Siemens AG',                                'DE0007236101', '723610', 'EUR', 'XETRA',  'STOCK'),
  ('ALV.DE',  'Allianz SE',                                'DE0008404005', '840400', 'EUR', 'XETRA',  'STOCK'),
  ('BAS.DE',  'BASF SE',                                   'DE000BASF111', 'BASF11', 'EUR', 'XETRA',  'STOCK'),
  ('DTE.DE',  'Deutsche Telekom AG',                       'DE0005557508', '555750', 'EUR', 'XETRA',  'STOCK'),
  ('VOW3.DE', 'Volkswagen AG Vorzuege',                    'DE0007664039', '766403', 'EUR', 'XETRA',  'STOCK'),
  ('ASML',    'ASML Holding N.V.',                         'NL0010273215', 'A1J4U4', 'USD', 'NASDAQ', 'STOCK'),
  ('MC.PA',   'LVMH Moet Hennessy Louis Vuitton SE',       'FR0000121014', '853292', 'EUR', 'EPA',    'STOCK'),
  ('EUNL.DE', 'iShares Core MSCI World UCITS ETF',         'IE00B4L5Y983', 'A0RPWH', 'EUR', 'XETRA',  'ETF'),
  ('VWCE.DE', 'Vanguard FTSE All-World UCITS ETF Acc',     'IE00BK5BQT80', 'A2PKXG', 'EUR', 'XETRA',  'ETF'),
  ('IMIE.DE', 'SPDR MSCI ACWI IMI UCITS ETF',              'IE00B44Z5B48', 'A1JJTD', 'EUR', 'XETRA',  'ETF'),
  ('EXXT.DE', 'iShares NASDAQ-100 UCITS ETF',              'DE000A0F5UF5', 'A0F5UF', 'EUR', 'XETRA',  'ETF'),
  ('IQQH.DE', 'iShares Global Clean Energy UCITS ETF',     'IE00B1XNHC34', 'A0MW0M', 'EUR', 'XETRA',  'ETF'),
  ('EUNA.DE', 'iShares Core Global Aggregate Bond UCITS',  'IE00B3RBWM25', 'A1JX52', 'EUR', 'XETRA',  'BOND'),
  ('SPY',     'SPDR S&P 500 ETF Trust',                    'US78462F1030', 'A0AET0', 'USD', 'NYSE',   'ETF'),
  ('^GSPC',   'S&P 500 Index',                             null,           null,     'USD', 'INDEX',  'INDEX'),
  ('^NDX',    'NASDAQ-100 Index',                          null,           null,     'USD', 'INDEX',  'INDEX'),
  ('^GDAXI',  'DAX Index',                                 null,           null,     'EUR', 'INDEX',  'INDEX'),
  ('BTC-EUR', 'Bitcoin / Euro',                            null,           null,     'EUR', 'CRYPTO', 'CRYPTO'),
  ('ETH-EUR', 'Ethereum / Euro',                           null,           null,     'EUR', 'CRYPTO', 'CRYPTO');
